apiVersion: v1
kind: Service
metadata:
  name: {{ include "yelb.fullname" . }}-db-headless
  labels:
    app: yelb-db
spec:
  clusterIP: None
  selector:
    app: yelb-db
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
