apiVersion: v1
kind: Service
metadata:
  name: {{ include "yelb.fullname" . }}-yelb-ui
spec:
  type: {{ .Values.service.type }}
  selector:
    app: yelb-ui
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
