apiVersion: v1
kind: Service
metadata:
  name: {{ include "yelb.fullname" . }}-redis-replicas-headless
  labels:
    app: redis-replicas
spec:
  clusterIP: None
  selector:
    app: redis-replica
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
