apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "yelb.fullname" . }}-redis-replica
  labels:
    app: redis-replica
spec:
  serviceName: {{ include "yelb.fullname" . }}-redis-replicas-headless
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: redis-replica
  template:
    metadata:
      labels:
        app: redis-replica
    spec:
      containers:
        - name: redis
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command:
            - sh
            - -c
            - |
              # configure as replica of master
              redis-server --protected-mode no --port 6379 --slaveof {{ $.Release.Name }}-redis-0 {{ 6379 }} --requirepass $REDIS_PASSWORD --masterauth $REDIS_PASSWORD
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $.Release.Name }}-global-secrets
                  key: redis_password
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-replica-data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: redis-replica-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
