apiVersion: v1
kind: Service
metadata:
  name: {{ include "yelb.fullname" . }}-redis-sentinel
spec:
  selector:
    app: redis-sentinel
  ports:
    - port: 26379
      targetPort: 26379
  type: ClusterIP
