apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-global-secrets
type: Opaque
stringData:
  postgres_password: {{ .Values.global.postgres.password | quote }}
  redis_password: {{ .Values.global.redis.password | quote }}
