apiVersion: v1
kind: Service
metadata:
  name: {{ include "yelb.fullname" . }}-db-replicas-headless
  labels:
    app: yelb-db-replica
spec:
  clusterIP: None
  selector:
    app: yelb-db-replica
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
