apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "yelb.fullname" . }}-db-replica
  labels:
    app: yelb-db-replica
spec:
  serviceName: {{ include "yelb.fullname" . }}-db-replicas-headless
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: yelb-db-replica
  template:
    metadata:
      labels:
        app: yelb-db-replica
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ $.Release.Name }}-global-secrets
                  key: postgres_password
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $.Release.Name }}-global-secrets
                  key: postgres_password
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: pgdata
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
